"""add collumn is_main to model ProductImage

Revision ID: ad9ae3d1dd3f
Revises: d33f6de12934
Create Date: 2025-06-22 07:48:16.741364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad9ae3d1dd3f'
down_revision: Union[str, None] = 'd33f6de12934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('is_main', sa.Boolean(), nullable=True))
    op.add_column('product_variants', sa.Column('material', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_variants', 'material')
    op.drop_column('product_images', 'is_main')
    # ### end Alembic commands ###
